### ISSUE TITLE
How to change the notes in the PianoRollModel?

### ISSUE THREAD

**Issue by AI-Guru** [AudioKit/PianoRoll#1]
Hi!

Congratulations on your fine package! It will be very useful for my work!

There is something that I did not get properly. Maybe you can help. What would be the way to add/remove the notes in PianoRollModel programatically?

Best,
Tristan

**Comment by wtholliday** [comment]
Hi Tristan,

  You can simply change the `PianoRollModel` and the UI will update automatically since it's an `ObservableObject`

cheers
